service: test-slsgo

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  apiKeys:
    - ${self:provider.stage}_${self:service}_xApiKey

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  ping:
    handler: bin/ping
    events:
      - http:
          path: ping
          method: get
          private: true
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-sam
